# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number6/number6.xci
# IP: The module: 'number6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number6/number6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'number6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number6/number6.xci
# IP: The module: 'number6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number6/number6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'number6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
