# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivado_files/vgatest/vgatest.cache/wt [current_project]
set_property parent.project_path E:/vivado_files/vgatest/vgatest.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivado_files/vgatest/vgatest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/二下/数电/数电大作业/VGA图片/pic2.coe
add_files E:/二下/数电/数电大作业/VGA图片/pic.coe
add_files e:/二下/数电/数电大作业/VGA图片/1.coe
add_files e:/二下/数电/数电大作业/VGA图片/4.coe
add_files e:/二下/数电/数电大作业/VGA图片/9.coe
read_verilog -library xil_defaultlib {
  E:/vivado_files/vgatest/vgatest.srcs/sources_1/new/calcu_tmp.v
  E:/vivado_files/vgatest/vgatest.src/sources/clock_vga.v
  E:/vivado_files/vgatest/vgatest.src/sources/image_generator.v
  E:/vivado_files/vgatest/vgatest.srcs/sources_1/new/tmp_bcd.v
  E:/vivado_files/vgatest/vgatest.src/sources/top.v
}
read_ip -quiet E:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/blk_mem_gen_0_3/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/blk_mem_gen_0_3/blk_mem_gen_0_ooc.xdc]

read_ip -quiet E:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number4/number4.xci
set_property used_in_implementation false [get_files -all e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number4/number4_ooc.xdc]

read_ip -quiet e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number9/number9.xci
set_property used_in_implementation false [get_files -all e:/vivado_files/vgatest/vgatest.srcs/sources_1/ip/number9/number9_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado_files/vgatest/vgatest.src/constraints/basys3_vga.xdc
set_property used_in_implementation false [get_files E:/vivado_files/vgatest/vgatest.src/constraints/basys3_vga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
